name: update-badges

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::gh
            any::jsonlite

      - name: Make svgs
        run: Rscript "update_badges.R"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: pkgsvgs
          git-config-name: ropenscibot
          git-config-email: accounts+ropenscibot@ropensci.org
