name: update-badges

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"
  issues:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - run: bundle install
    
    - name: Make svgs
      run: ruby update_badges.rb

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.5.7
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: pkgsvgs
